### PR TITLE
unit test for secondary target

### PR DESCRIPTION
**Pull request by DaanHoogland**

### CODE REVIEW

**Comment by DaanHoogland** [comment]
H Mike, just my one usecase but nice boiler plate for others.

**Comment by DaanHoogland** [comment]
ping @mike-tutkowski

**Comment by yadvr** [comment]
@mike-tutkowski can you review/merge this unit test mike? wrt PR: https://github.com/apache/cloudstack/pull/2776#discussion_r208471311

**Comment by mike-tutkowski** [comment]
Thanks @DaanHoogland - I've included your unit test. Feel free to delete this branch.

**Comment by mike-tutkowski** [comment]
Ignore my prior comment (which I deleted), I went ahead and performed a Merge. Thanks, @DaanHoogland!

**Pull request merged**
